### ISSUE TITLE
screen 중복

### ISSUE THREAD

**Issue by allity** [ppeper/Hear_dev#2]
meeting.js
app.js

screen method 중복, screen 변수 중복 선언

meeting.ejs 에서 meeting.js script 주석처리 해놓음

**Comment by allity** [comment]
> meeting.js app.js
> 
> screen method 중복, screen 변수 중복 선언
> 
> meeting.ejs 에서 meeting.js script 주석처리 해놓음

**Comment by Sxbxn** [comment]
merge conflict
